name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: configure
      run: |
        sudo apt install gcc make gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu autoconf -y
        autoreconf
        ./configure --build x86_64-pc-linux-gnu --host aarch64-linux-gnu CFLAGS="-static" --enable-mpers=check --prefix=`pwd`/build
      
      
    - name: make
      run: make LDFLAGS="-all-static"
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
          name: openssh-android
          path: build/*
